// aiops-infrastructure/src/main/java/top/codejava/aiops/infrastructure/adapter/DynamicRemoteBrainAdapter.java
package top.codejava.aiops.infrastructure.adapter;

import dev.langchain4j.model.chat.ChatLanguageModel;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import top.codejava.aiops.application.port.LlmRemoteBrainPort;
import top.codejava.aiops.domain.model.PlanDraft;
import top.codejava.aiops.domain.model.ProjectContext;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * 动态远程AI大脑适配器
 * 依赖注入标准的 ChatLanguageModel 接口，不硬编码具体提供商
 * 遵循依赖倒置原则：依赖抽象（ChatLanguageModel），不依赖具体实现
 */
@Slf4j
@RequiredArgsConstructor
public class DynamicRemoteBrainAdapter implements LlmRemoteBrainPort {

    /**
     * 远程AI模型（由Spring根据配置动态注入）
     */
    private final ChatLanguageModel remoteChatModel;

    /**
     * 本地AI模型（用于安全审计，由Spring根据配置动态注入）
     */
    private final ChatLanguageModel localChatModel;

    @Override
    public PlanDraft generateDeploymentPlan(ProjectContext context) {
        String prompt = buildGenerationPrompt(context);
        String response = remoteChatModel.generate(prompt);

        return PlanDraft.builder()
                .generatedAt(LocalDateTime.now())
                .rawResponse(response)
                // 解析响应提取结构化信息的简化版本
                // 完整实现可使用Parser提取结构化数据
                .architectureSummary(extractSummary(response))
                .dockerfileContent(extractDockerfile(response))
                .auditPassed(false)
                .build();
    }

    @Override
    public PlanDraft auditPlan(PlanDraft planDraft) {
        String prompt = buildAuditPrompt(planDraft);
        String response = localChatModel.generate(prompt);

        // 简化审计逻辑：检查响应中是否包含"通过"或"approved"关键词
        boolean passed = response.toLowerCase().contains("通过") ||
                         response.toLowerCase().contains("approved") ||
                         response.toLowerCase().contains("pass");

        List<String> findings = parseAuditFindings(response);

        planDraft.setAuditPassed(passed);
        planDraft.setAuditFindings(findings);

        return planDraft;
    }

    /**
     * 构建生成提示词
     */
    private String buildGenerationPrompt(ProjectContext context) {
        return String.format("""
                You are an experienced DevOps engineer. Please help me generate a deployment plan for this project.

                Project context detected:
                - Primary language: %s
                - Build tool: %s
                - Has Dockerfile: %b
                - Has docker-compose: %b
                - Estimated lines of code: %d
                - Config files found: %s

                Please provide:
                1. A brief architecture summary
                2. Recommended deployment approach
                3. A complete Dockerfile if not present
                4. A complete docker-compose.yml if needed

                Format your response in clear markdown.
                """,
                context.getPrimaryLanguage(),
                context.getBuildTool(),
                context.isHasDockerfile(),
                context.isHasDockerCompose(),
                context.getEstimatedLinesOfCode(),
                context.getConfigFiles() != null ? String.join(", ", context.getConfigFiles()) : "none"
        );
    }

    /**
     * 构建审计提示词
     */
    private String buildAuditPrompt(PlanDraft draft) {
        return String.format("""
                You are a security auditor reviewing a Dockerfile and deployment configuration generated by another AI.

                Please review the following generated deployment plan for security issues:

                --- BEGIN GENERATED PLAN ---
                %s
                --- END GENERATED PLAN ---

                Check for:
                1. Running containers as root
                2. Exposed secrets or credentials
                3. Unpinned image versions that could lead to supply chain attacks
                4. Unnecessary open ports
                5. Lack of .dockerignore recommendations
                6. Any other security best practice violations

                End your response with either: AUDIT PASSED or AUDIT FAILED.
                If FAILED, list the specific findings.
                """, draft.getRawResponse()
        );
    }

    /**
     * 简易提取摘要
     */
    private String extractSummary(String response) {
        // 简化实现，取前几段作为摘要
        String[] lines = response.split("\\R", 10);
        StringBuilder summary = new StringBuilder();
        for (int i = 0; i < Math.min(5, lines.length); i++) {
            summary.append(lines[i]).append("\n");
        }
        return summary.toString().trim();
    }

    /**
     * 提取 Dockerfile 内容
     */
    private String extractDockerfile(String response) {
        // 查找代码块标记
        int dockerfileStart = response.toLowerCase().indexOf("dockerfile");
        if (dockerfileStart == -1) {
            return null;
        }
        int codeBlockStart = response.indexOf("```", dockerfileStart);
        if (codeBlockStart == -1) {
            return null;
        }
        int codeBlockEnd = response.indexOf("```", codeBlockStart + 3);
        if (codeBlockEnd == -1) {
            return response.substring(codeBlockStart + 3).trim();
        }
        return response.substring(codeBlockStart + 3, codeBlockEnd).trim();
    }

    /**
     * 解析审计结果
     */
    private List<String> parseAuditFindings(String response) {
        List<String> findings = new ArrayList<>();
        // 简化实现，按行切分寻找以"-"或"*"开头的行作为发现项
        for (String line : response.split("\\R")) {
            String trimmed = line.trim();
            if (trimmed.startsWith("-") || trimmed.startsWith("*")) {
                findings.add(trimmed.substring(1).trim());
            }
        }
        return findings;
    }
}
